### ISSUE TITLE
Fork contributions?

### ISSUE THREAD

**Issue by Neustradamus** [paldier/ax3600_tool#14]
@paldier: It will be nice to add fork contributions, no?
- @ericwang2006: https://github.com/ericwang2006/ax3600_tool
- @tevenfeng: https://github.com/tevenfeng/ax3600_tool

Happy New Year 2022 to all!

**Comment by paldier** [comment]
I have done it, but it's better to create a pull request.

**Comment by Neustradamus** [comment]
@paldier: Yes but there was not...

About @tevenfeng, not good?

**Comment by tevenfeng** [comment]
> @paldier: Yes but there was not...
> 
> About @tevenfeng, not good?

Well, my fork just simply add a firmware for Xiaomi AX1800, which could be used to unlock SSH. There's no other change actually.
