### ISSUE TITLE
最后CRC32校验那里是不是有问题

### ISSUE THREAD

**Issue by jmwangde** [paldier/ax3600_tool#3]
hxd算的CRC-32 (以太网和 PKZIP): 0BF3D9BF,应该填BF D9 F3 0B吧,这个工具填的是0F 9B 3D BF,不知道是否有错误还是两种都可以?mtd9的其他内容我自己改的都是一样的

**Comment by paldier** [comment]
确实是代码bug，第一位是0x0X的确实有问题
